name: Tests

on: [pull_request, push]

jobs:
  xcode-tests:
    name: "Tests"
    runs-on: macos-11

    strategy:
      matrix:
        platform: [iOS, iPad]
        include:
          - platform: iOS
            sdk: iphonesimulator
            destination: "name=iPhone 12"

          - platform: iPad
            sdk: iphonesimulator
            destination: "name=iPad Pro (9.7-inch)"

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Set xCode 13.2
      uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: '13.2'

    - name: Run xcodebuild
      run: |
        xcodebuild -project RemoteJobsBoard.xcodeproj -scheme RemoteJobsBoard -destination "${{ matrix.destination }}" -resultBundlePath foo.xcresult -enableCodeCoverage YES -sdk ${{ matrix.sdk }} test

    - name: Run poc
      run: |
        npm install
        node ./generate-codecov-json.js --archive-path ./foo.xcresult/

    - name: Upload Coverage to CodeCov
      uses: codecov/codecov-action@v3
