name: Tests

on: [pull_request, push]

jobs:
  xcode-tests:
    name: "Tests"
    runs-on: macos-11

    strategy:
      matrix:
        platform: [iOS, iPad]
        include:
          - platform: iOS
            sdk: iphonesimulator
            destination: "name=iPhone 12"

          - platform: iPad
            sdk: iphonesimulator
            destination: "name=iPad Pro (9.7-inch)"

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Set xCode 13.2
      uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: '13.2'

    - name: Xcodebuild Action
      uses: sersoft-gmbh/xcodebuild-action@v1
      with:
        action: test
        project: RemoteJobsBoard.xcodeproj
        scheme: RemoteJobsBoard
        sdk: ${{ matrix.sdk }}
        destination: "${{ matrix.destination }}"
        enable-code-coverage: true
        use-xcpretty: true

    - name: Run poc
      run: node ./generate-codecov-json.js

    - name: Upload Coverage to CodeCov
      uses: codecov/codecov-action@v3
